# XOtheme Configuration
title = "XOtheme"
description = "A clean, accessible, and performant portfolio site"
base_url = "https://xostd.com"

# Language and locale
default_language = "en"

# Build settings
compile_sass = false  # We handle this with our npm script
minify_html = true
build_search_index = true
generate_feeds = true

# Markdown configuration
[markdown]
highlight_code = true
highlight_theme = "css"  # Use CSS classes instead of inline styles
highlight_themes_css = [
  { theme = "base16-ocean-light", filename = "syntax-theme-light.css" },
  { theme = "base16-ocean-dark", filename = "syntax-theme-dark.css" },
]
render_emoji = true
external_links_target_blank = true
external_links_no_follow = true
external_links_no_referrer = true

# Slugify configuration
[slugify]
paths = "on"
taxonomies = "on"
anchors = "on"

# Search configuration
[search]
include_title = true
include_description = true
include_content = true

# Site metadata
[extra]
author = "Harshad Sharma"
email = "harshad@sharma.io"
github = "xostack"
mastodon = "hiway@mastodon.social"

# Navigation
[[extra.nav]]
name = "Home"
url = "/"

[[extra.nav]]
name = "About"
url = "/about/"

[[extra.nav]]
name = "Projects"
url = "/projects/"

[[extra.nav]]
name = "Journal"
url = "/journal/"
